name: Python CI Pipeline  # Name of the pipeline

on: 
  push:  # Runs on every push to the repository
    branches:
      - main  # Runs only on the 'main' branch
  pull_request:  # Runs on pull requests targeting the 'main' branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the pipeline on an Ubuntu Linux machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # This action gets the latest code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # This action sets up Python on the machine
        with:
          python-version: '3.10'  # You can change this to your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies if requirements.txt exists

      - name: Run Tests
        run: |
          pytest || echo "No tests found, skipping..."  # Run tests if they exist using pytest

